### PR TITLE
Fix Python 3.8 SyntaxWarning

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/pchomik/pytest-spec/issues/26

### CODE REVIEW

**Comment by rafa-acioly** [comment]
can someone merge this?

**Comment by jayvdb** [comment]
ping @pchomik

**Comment by pchomik** [comment]
Yes. I will do that tomorrow. @jayvdb thank you for fix.

**Comment by cgurnik** [comment]
Hi @pchomik, could we get this merged and a new version released? Thanks in advance!

**Pull request merged**
